runtime: python37

env: standard
instance_class: F2

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 2